// packages/clavicula-angular/index.js
export * from '@grimoire-intel/clavicula';
import { Observable } from 'rxjs';
import { signal } from '@angular/core';

/**
 * Converts a Clavicula store to an RxJS Observable.
 * @param {import('clavicula').Store<T> | import('clavicula').DerivedStore<T>} store
 * @returns {Observable<T>} Observable that emits on store changes
 * @template T
 */
export function toObservable(store) {
  return new Observable(subscriber => {
    // subscribe() calls immediately with current value, so no need to emit first
    return store.subscribe(val => subscriber.next(val));
  });
}

/**
 * Converts a Clavicula store to an Angular Signal.
 * @param {import('clavicula').Store<T> | import('clavicula').DerivedStore<T>} store
 * @returns {{ signal: import('@angular/core').Signal<T>, destroy: () => void }}
 * @template T
 */
export function toSignal(store) {
  const sig = signal(store.get());
  const unsub = store.subscribe(val => sig.set(val));
  return { signal: sig.asReadonly(), destroy: unsub };
}

// packages/clavicula-solid/index.js
export * from '@grimoire-intel/clavicula';
import { createSignal, onCleanup } from 'solid-js';

/**
 * Solid primitive to subscribe to a Clavicula store.
 * @param {import('clavicula').Store<T> | import('clavicula').DerivedStore<T>} store
 * @returns {import('solid-js').Accessor<T>} Accessor for current store state
 * @template T
 */
export function useStore(store) {
  const [state, setState] = createSignal(store.get());
  const unsub = store.subscribe(setState);
  onCleanup(unsub);
  return state;
}
